class ComuneDiNascita:

    def __init__(self, luogo_nascita, provincia):
        self.luogo_nascita = luogo_nascita
        self.provincia = provincia

    def codice_catastale(self):
        codici_catastali = {
            "Roma": "H501",
            "Milano": "F205",
            "Napoli": "F839",
            "Torino": "L219",
            "Firenze": "D612",
            "Bologna": "A944",
            "Venezia": "L736",
            "Genova": "D969",
            "Palermo": "G273",
            "Catania": "C351",
            "Verona": "L781",
            "Trieste": "L424",
            "Bari": "A662",
            "Cagliari": "B354",
            "Perugia": "G478",
            "Ancona": "A271",
            "Trento": "L378",
            "Bolzano": "A952",
            "Parma": "G337",
            "Reggio Emilia": "H223",
            "Pescara": "G482",
            "Rimini": "H294",
            "Salerno": "H703",
            "Messina": "F158",
            "Livorno": "E625",
            "Padova": "G224",
            "Taranto": "L049",
            "Lecce": "E506",
            "Modena": "F257",
            "Udine": "L483",
            "Siracusa": "I754",
            "Aosta": "A326",
            "Sassari": "I452",
            "Ferrara": "D548",
            "Bergamo": "A794",
            "Monza": "F704",
            "Como": "C933",
            "Lucca": "E715",
            "Pisa": "G702",
            "Ravenna": "H199",
            "Treviso": "L407",
            "Vicenza": "L840",
            "Cremona": "D150",
            "Mantova": "E897",
            "Arezzo": "A390",
            "Siena": "I726",
            "Grosseto": "E202",
            "Pistoia": "G713",
        }
        codici_catastali_esteri = {
            "ALBANIA": "Z100",
            "ALGERIA": "Z101",
            "ANDORRA": "Z102",
            "ANGOLA": "Z103",
            "ARGENTINA": "Z104",
            "ARMENIA": "Z105",
            "AUSTRALIA": "Z106",
            "AUSTRIA": "Z107",
            "AZERBAIGIAN": "Z108",
            "BANGLADESH": "Z109",
            "BELGIO": "Z110",
            "BIELORUSSIA": "Z111",
            "BOLIVIA": "Z112",
            "BOSNIA-ERZEGOVINA": "Z113",
            "BRASILE": "Z114",
            "BULGARIA": "Z115",
            "CANADA": "Z116",
            "CINA": "Z210",
            "COLOMBIA": "Z118",
            "COREA DEL NORD": "Z119",
            "COREA DEL SUD": "Z120",
            "COSTA D'AVORIO": "Z121",
            "CROAZIA": "Z122",
            "CUBA": "Z123",
            "DANIMARCA": "Z124",
            "EGITTO": "Z125",
            "EMIRATI ARABI UNITI": "Z126",
            "ECUADOR": "Z127",
            "ESTONIA": "Z128",
            "ETIOPIA": "Z129",
            "FILIPPINE": "Z130",
            "FINLANDIA": "Z131",
            "FRANCIA": "Z132",
            "GERMANIA": "Z133",
            "GIAPPONE": "Z250",
            "GIORDANIA": "Z135",
            "GRECIA": "Z136",
            "INDIA": "Z260",
            "INDONESIA": "Z138",
            "IRAN": "Z139",
            "IRAQ": "Z140",
            "IRLANDA": "Z141",
            "ISLANDA": "Z142",
            "ISRAELE": "Z143",
            "KAZAKISTAN": "Z144",
            "KENYA": "Z145",
            "KIRGHIZISTAN": "Z146",
            "LIBANO": "Z147",
            "LIBIA": "Z148",
            "LIECHTENSTEIN": "Z149",
            "LITUANIA": "Z150",
            "LUSSEMBURGO": "Z151",
            "MACEDONIA": "Z152",
            "MALAYSIA": "Z153",
            "MALTA": "Z154",
            "MAROCCO": "Z330",
            "MESSICO": "Z156",
            "MONACO": "Z157",
            "MONGOLIA": "Z158",
            "MONTENEGRO": "Z159",
            "NORVEGIA": "Z160",
            "NUOVA ZELANDA": "Z161",
            "OLANDA (PAESI BASSI)": "Z162",
            "PAKISTAN": "Z163",
            "POLONIA": "Z164",
            "PORTOGALLO": "Z165",
            "REGNO UNITO": "Z166",
            "REPUBBLICA CECA": "Z167",
            "REPUBBLICA DOMINICANA": "Z168",
            "ROMANIA": "Z169",
            "RUSSIA": "Z170",
            "SERBIA": "Z171",
            "SINGAPORE": "Z172",
            "SLOVACCHIA": "Z173",
            "SLOVENIA": "Z174",
            "SPAGNA": "Z175",
            "STATI UNITI": "Z404",
            "SVEZIA": "Z177",
            "SVIZZERA": "Z178",
            "THAILANDIA": "Z179",
            "TUNISIA": "Z180",
            "TURCHIA": "Z181",
            "UCRAINA": "Z182",
            "UNGHERIA": "Z183",
            "URUGUAY": "Z184",
            "UZBEKISTAN": "Z185",
            "VENEZUELA": "Z186",
            "VIETNAM": "Z187",
            "ZIMBABWE": "Z188"
        }

        if self.luogo_nascita in codici_catastali:
            return codici_catastali[self.luogo_nascita]
        elif self.luogo_nascita in codici_catastali_esteri:
            return codici_catastali_esteri[self.luogo_nascita]

obj = ComuneDiNascita("Messina", "Me")
print(obj.codice_catastale())

obj1 = ComuneDiNascita("Marocco", "MA")
print(obj1.codice_catastale())